### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by argentini** [DQNEO/apple-dictionary-parser#1]

**Comment by DQNEO** [comment]
@argentini Thank you for reporting it ! I've fixed the issue by #3 . Could you check it please ?

**Comment by argentini** [comment]
**Thanks for taking a look at this!** It appears to be working now, though there are some other issues...

1. htmlsplit mode does not work. It reports back that there are no help topics for 'htmlsplit'
2. Your example for running the tool after installation needs to include the path to the tool, for example: `~/go/bin/apple-dictionary-parser dump`
3. Your examples for text and html and such need to use file output piping, for example: `~/go/bin/apple-dictionary-parser text > ~/Desktop/all.txt`

**Comment by DQNEO** [comment]
Thank you for reporting more issues! Let me check one by one.

**Comment by DQNEO** [comment]
> htmlsplit mode does not work. It reports back that there are no help topics for 'htmlsplit'

Yes the README was wrong and I've fixed it in ae70a86 .  It should be `html-split`

**Comment by DQNEO** [comment]
> Your example for running the tool after installation needs to include the path to the tool, for example: ~/go/bin/apple-dictionary-parser dump

Added a explanation in 4f6e0a1

Basically, this is not specific to my tool but golang in general.

**Comment by DQNEO** [comment]
> Your examples for text and html and such need to use file output piping, for example: ~/go/bin/apple-dictionary-parser text ~/Desktop/all.txt

Fixed it at d949510

**Comment by DQNEO** [comment]
I think "No longer working" issue itself has been solved. Please feel free to create any new issue if you find anything.
Thank you for reporting !

**Comment by argentini** [comment]
Perfect - thanks again! Agreed - close this puppy.
